# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1016, 773)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.btn_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout.addWidget(self.btn_search)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(300, 0))
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget_biquge = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_biquge.setObjectName("tableWidget_biquge")
        self.tableWidget_biquge.setColumnCount(4)
        self.tableWidget_biquge.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_biquge.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_biquge.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_biquge.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_biquge.setHorizontalHeaderItem(3, item)
        self.gridLayout_2.addWidget(self.tableWidget_biquge, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget_biquge_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_biquge_2.setObjectName("tableWidget_biquge_2")
        self.tableWidget_biquge_2.setColumnCount(4)
        self.tableWidget_biquge_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_biquge_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_biquge_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_biquge_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_biquge_2.setHorizontalHeaderItem(3, item)
        self.gridLayout_4.addWidget(self.tableWidget_biquge_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget_shuquge = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget_shuquge.setObjectName("tableWidget_shuquge")
        self.tableWidget_shuquge.setColumnCount(4)
        self.tableWidget_shuquge.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_shuquge.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_shuquge.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_shuquge.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_shuquge.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.tableWidget_shuquge, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget_miaojiang = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_miaojiang.setObjectName("tableWidget_miaojiang")
        self.tableWidget_miaojiang.setColumnCount(4)
        self.tableWidget_miaojiang.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_miaojiang.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_miaojiang.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_miaojiang.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_miaojiang.setHorizontalHeaderItem(3, item)
        self.gridLayout_3.addWidget(self.tableWidget_miaojiang, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableWidget_wuyou = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_wuyou.setObjectName("tableWidget_wuyou")
        self.tableWidget_wuyou.setColumnCount(4)
        self.tableWidget_wuyou.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_wuyou.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_wuyou.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_wuyou.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_wuyou.setHorizontalHeaderItem(3, item)
        self.gridLayout_5.addWidget(self.tableWidget_wuyou, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "小说下载工具"))
        self.btn_search.setText(_translate("MainWindow", "搜索"))
        self.tabWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.tabWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        item = self.tableWidget_biquge.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "书名"))
        item = self.tableWidget_biquge.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "作者"))
        item = self.tableWidget_biquge.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "最新章节"))
        item = self.tableWidget_biquge.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "下载"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "笔趣阁"))
        item = self.tableWidget_biquge_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "书名"))
        item = self.tableWidget_biquge_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "作者"))
        item = self.tableWidget_biquge_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "最新章节"))
        item = self.tableWidget_biquge_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "下载"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "笔趣阁2"))
        item = self.tableWidget_shuquge.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "书名"))
        item = self.tableWidget_shuquge.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "作者"))
        item = self.tableWidget_shuquge.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "最新章节"))
        item = self.tableWidget_shuquge.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "下载"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "书趣阁"))
        item = self.tableWidget_miaojiang.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "书名"))
        item = self.tableWidget_miaojiang.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "作者"))
        item = self.tableWidget_miaojiang.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "最新章节"))
        item = self.tableWidget_miaojiang.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "下载"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "苗疆"))
        item = self.tableWidget_wuyou.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "书名"))
        item = self.tableWidget_wuyou.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "作者"))
        item = self.tableWidget_wuyou.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "最新章节"))
        item = self.tableWidget_wuyou.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "下载"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "无忧书城"))
